### ISSUE TITLE
Can't find Python executable

### ISSUE THREAD

**Issue by zspri** [23phy/ewc#6]
![image](https://discord-is-down.party/BxSF4XSD.png)

Happens when trying to install through npm... The file path is in the PATH variable

**Comment by arek-kwapis** [comment]
Try executing this command:

`npm install --global --production windows-build-tools`

Can confirm it works and fixes the issue. 

If it does not work, check the original issue [here](https://github.com/felixrieseberg/windows-build-tools/issues/56)

**Comment by zspri** [comment]
Now this error is given:
```
PS D:\Files\Git\Applications\test> npm i electron-acrylic

> electron-acrylic@0.0.4 preinstall D:\Files\Git\Applications\test\node_modules\electron-acrylic
> echo This is a work in progress. There may/will be bugs. You can open an issue at https://github.com/23phy/electron-acrylic/issues'

This is a work in progress. There may/will be bugs. You can open an issue at https://github.com/23phy/electron-acrylic/issues'

> electron-acrylic@0.0.4 postinstall D:\Files\Git\Applications\test\node_modules\electron-acrylic
> npm run rebuild


> electron-acrylic@0.0.4 rebuild D:\Files\Git\Applications\test\node_modules\electron-acrylic
> node-gyp rebuild --target=2.0.0 --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell


D:\Files\Git\Applications\test\node_modules\electron-acrylic>if not defined npm_config_node_gyp (node "D:\Programs\NodeJS\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --target=2.0.0 --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell )  else (node "D:\Programs\NodeJS\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --target=2.0.0 --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\Files\Git\Applications\test\node_modules\node-addon-api\src\nothing.vcxproj(20,3): error MSB4019: The imported proje
ct "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and th
at the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Programs\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17738
gyp ERR! command "D:\\Programs\\NodeJS\\node.exe" "D:\\Programs\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.0" "--runtime=electron" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd D:\Files\Git\Applications\test\node_modules\electron-acrylic
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-acrylic@0.0.4 rebuild: `node-gyp rebuild --target=2.0.0 --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-acrylic@0.0.4 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-08-24T22_32_55_618Z-debug.log
npm WARN test@0.1.0 No description
npm WARN test@0.1.0 No repository field.
npm WARN test@0.1.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-acrylic@0.0.4 postinstall: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-acrylic@0.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-08-24T22_32_55_746Z-debug.log
```

**Comment by arek-kwapis** [comment]
Can you take me through all the steps you have done to achieve this? This includes if your using it as standalone or as a dependency , and the fix I provided. Try to give me as much detail as possible, and don't miss out steps, as what may seem insignificant may be major; I will be attempting to reproduce this exact error on a clean VM environment.

**Comment by zspri** [comment]
I installed windows-build-tools just as you said (`npm i -g --production windows-build-tools`) in my electron project's directory through a Powershell window as admin, then entered `npm i electron-acrylic` in the same folder as a dependency.

System info:
Windows 10 Home x64 10.0.17738 (version 1803 pre-release)
Electron version: v2.0.4
NodeJS version: v10.6.0
npm version: v6.1.0

Do you need the npm debug log from the install?

**Comment by arek-kwapis** [comment]
Alright, I've noted the details. Will try it out as soon as possible. It may take a day or two due to College/Work, but I will try to find a fix as fast as possible.
