### ISSUE TITLE
"Couldn't find specified module."

### ISSUE THREAD

**Issue by gspalato** [23phy/ewc#7]
(Note: I followed all steps.)
When I require the module and apply the .setAcrylic, it errors. The error seems to be a failed relative path that includes `\\?\` before the actual path for some reason.

Error: 
`Error: Couldn't find specified module.
\\?\C:\Users\hinok\Workspace\Scar\node_modules\electron-acrylic\build\Release\ElectronAcrylic.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (C:\Users\hinok\Workspace\Scar\node_modules\electron-acrylic\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (C:\Users\hinok\Workspace\Scar\node_modules\electron-acrylic\index.js:1:199)
`
![image](https://user-images.githubusercontent.com/3950465/50936710-f2d0ef00-1457-11e9-81d4-7737f59e2bb3.png)

**Comment by 23phy** [comment]
Hello 🤔

Do you `import` or `require` it? 
Also, can you post the snippet where you require/import it and where you use it (where you call the function `setAcrylic()`.

**Comment by 23phy** [comment]
If you could wait one or two days.. I'm in the process of  rewriting the whole module.

**Comment by gspalato** [comment]
Oh, yes. I require it at the start of the script. Here's a snippet of how I do it:

https://gist.github.com/gspalato/76c7095ff6bc5f43a3907bb8f12006d4

**Comment by SamyzKhalil** [comment]
In `node_modules\electron-acrylic\package.json`

change `--target=2.0.0` to your electron version

then rebuild the module `npm rebuild electron-acrylic`

**Comment by 23phy** [comment]
Seems like the issue was that you had to compile the module for your node version. Issue closed.
